import { boolean } from '@hapi/joi';
import mongoose from 'mongoose';
const Schema = mongoose.Schema;
const userSchema=new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    Email:{
        type:String,
        unique:true,
        required:true
    },
    Password:{
        type:String,
        required:true
    },
    bloodGroup:{
        type:String
    },
    covidTestDate:{
        type:Date
    },
    Report:{
        type:String
    },
    coronaType:{
        type:String
    },
    doctorName:{
        type:String
    },
    hospitalName:{
        type:String
    },
    covidCuredDate:{
        type:Date
    },
    Gender:{
        type:String,
        required:true
    },
    Age:{
        type:Number,
        required:true
    },
    Contact:{
        type:Number
    },
    Address:{
        type:String
    },
    idProof:{
        type:String
    },
    Willing:{
        type:Boolean
    },
    createdDate:{
        type:Date,
        required:true
    },
    isActive:{
        type:Boolean,
        required:true
    },
    Role:{
        type:String,
        required:true
    },
    City:{
        type:String
    },
    State:{
        type:String
    }
},{collection:'users'});
export default new mongoose.model('user',userSchema);